export const FETCH_DETECTION_SUCCESS = 'FETCH_DETECTION_SUCCESS';
export const FETCH_DETECTION_FAILURE = 'FETCH_DETECTION_FAILURE';
export const FETCH_DETECTION_DIAGNOSIS_SUCCESS = 'FETCH_DETECTION_DIAGNOSIS_SUCCESS';
export const FETCH_DETECTION_DIAGNOSIS_FAILURE = 'FETCH_DETECTION_DIAGNOSIS_FAILURE';
