// redux/actions/types.js

export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_FAILURE = 'FETCH_PATIENTS_FAILURE';

export const FETCH_PATIENTS_DASHBOARD_SUCCESS = 'FETCH_PATIENTS_DASHBOARD_SUCCESS';
export const FETCH_PATIENTS_DASHBOARD_FAILURE = 'FETCH_PATIENTS_DASHBOARD_FAILURE';

export const FETCH_PATIENTS_MALIGNUS_SUCCESS = 'FETCH_PATIENTS_MALIGNUS_SUCCESS';
export const FETCH_PATIENTS_MALIGNUS_FAILURE = 'FETCH_PATIENTS_MALIGNUS_FAILURE';