
export const FETCH_MONITOR_SUCCESS = 'FETCH_MONITOR_SUCCESS';
export const FETCH_MONITOR_FAILURE = 'FETCH_MONITOR_FAILURE';

export const FETCH_OBJECT_SUCCESS = 'FETCH_OBJECT_SUCCESS';
export const FETCH_OBJECT_FAILURE = 'FETCH_OBJECT_FAILURE';