// redux/actions/types.js

export const FETCH_PRIVILEGIOS_SUCCESS = 'FETCH_PRIVILEGIOS_SUCCESS';
export const FETCH_PRIVILEGIOS_FAILURE = 'FETCH_PRIVILEGIOS_FAILURE';

export const FETCH_BOTONES_SUCCESS = 'FETCH_BOTONES_SUCCESS';
export const FETCH_BOTONES_FAILURE = 'FETCH_BOTONES_FAILURE';

export const FETCH_INFOUSER_SUCCESS = 'FETCH_INFOUSER_SUCCESS';
export const FETCH_INFOUSER_FAILURE = 'FETCH_INFOUSER_FAILURE';